name: Check

on:
  push:
    branches: [ '*' ]  # 触发所有分支的推送事件
  pull_request:
    branches: [ '*' ]  # 触发所有分支的拉取请求事件

  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
